name: nanoai
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _r-mutex=1.0.0=anacondar_1
  - _tflow_180_select=1.0=gpu
  - _tflow_select=1.2.0=mkl
  - absl-py=0.7.1=py36_0
  - astor=0.7.1=py36_0
  - bcftools=1.8=h4da6232_3
  - binutils_impl_linux-64=2.28.1=had2808c_3
  - binutils_linux-64=7.2.0=had2808c_27
  - biopython=1.74=py36h7b6447c_0
  - blas=1.0=mkl
  - bleach=1.5.0=py36_0
  - bokeh=1.4.0=py36_0
  - bwidget=1.9.11=1
  - bzip2=1.0.6=h14c3975_5
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.11.28=py36_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.3.1=cuda10.0_0
  - cupti=10.0.130=0
  - curl=7.64.1=hbc83047_0
  - cycler=0.10.0=py36_0
  - cython=0.29.7=py36he6710b0_0
  - dbus=1.13.12=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - future=0.17.1=py36_0
  - gast=0.2.2=py36_0
  - gcc_impl_linux-64=7.2.0=habb00fd_3
  - gcc_linux-64=7.2.0=h550dcbe_27
  - gfortran_impl_linux-64=7.2.0=hdf63c60_3
  - gfortran_linux-64=7.2.0=h550dcbe_27
  - git=2.20.1=pl526hacde149_0
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - gsl=2.4=h14c3975_4
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.2.0=hdf63c60_3
  - gxx_linux-64=7.2.0=h550dcbe_27
  - h5py=2.9.0=py36h7918eee_0
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.4=hb1b8bf9_0
  - html5lib=0.9999999=py36_0
  - htslib=1.9=h4da6232_3
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.3=199
  - jinja2=2.10.1=py36_0
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.1.0=py36he6710b0_0
  - krb5=1.16.1=h173b8e3_7
  - libcurl=7.64.1=h20c2e04_0
  - libdeflate=1.2=h516909a_1
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.7.1=hd408876_0
  - libssh2=1.8.2=h1ba5d50_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - make=4.2.1=h1bed415_1
  - mappy=2.17=py36h84994c4_0
  - markdown=3.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.3=py36_0
  - matplotlib-base=3.1.3=py36hef1b27d_0
  - minimap2=2.17=h8b12597_1
  - mkl=2019.3=199
  - mkl_fft=1.0.12=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - nanoget=1.12.0=py_0
  - nanomath=0.23.1=py_1
  - nanoplot=1.28.2=py_0
  - nanoqc=0.9.2=py_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.16.3=py36h7e9f1db_0
  - numpy-base=1.16.3=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - ont-tombo=1.5=py36r351h24bf2e0_1
  - openssl=1.1.1=h7b6447c_0
  - packaging=20.1=py_0
  - pandas=0.24.2=py36hf484d3e_0
  - pango=1.42.4=h049681c_0
  - patsy=0.5.1=py_0
  - pauvre=0.1.86=py_1
  - pcre=8.43=he6710b0_0
  - perl=5.26.2=h14c3975_0
  - pillow=6.2.0=py36h34e0f95_0
  - pip=19.1.1=py36_0
  - pixman=0.38.0=h7b6447c_0
  - plotly=4.4.1=py_0
  - protobuf=3.7.1=py36he6710b0_0
  - pyfaidx=0.5.5.2=py_1
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pysam=0.11.2.2=py36_1
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py_0
  - pytz=2019.1=py_0
  - pyyaml=5.3=py36h7b6447c_0
  - qt=5.9.7=h5867ecd_1
  - r-assertthat=0.2.0=r351h6115d3f_0
  - r-base=3.5.1=h1e0a451_2
  - r-bh=1.66.0_1=r351h6115d3f_0
  - r-bindr=0.1.1=r351h6115d3f_0
  - r-bindrcpp=0.2.2=r351h29659fb_0
  - r-bit=1.1_14=r351hd10c6a6_0
  - r-bit64=0.9_7=r351hd10c6a6_0
  - r-blob=1.1.1=r351hf348343_0
  - r-cli=1.0.0=r351h6115d3f_1
  - r-colorspace=1.3_2=r351h96ca727_0
  - r-crayon=1.3.4=r351h6115d3f_0
  - r-dbi=1.0.0=r351h6115d3f_0
  - r-dbplyr=1.2.2=r351hf348343_0
  - r-dichromat=2.0_0=r351h6115d3f_4
  - r-digest=0.6.15=r351h96ca727_0
  - r-dplyr=0.7.6=r351h29659fb_0
  - r-fansi=0.2.3=r351h96ca727_0
  - r-ggplot2=3.0.0=r351h6115d3f_0
  - r-glue=1.3.0=r351h96ca727_0
  - r-gridextra=2.3=r351h6115d3f_0
  - r-gtable=0.2.0=r351h6115d3f_0
  - r-labeling=0.3=r351h6115d3f_4
  - r-lattice=0.20_35=r351h96ca727_0
  - r-lazyeval=0.2.1=r351h96ca727_0
  - r-magrittr=1.5=r351h6115d3f_4
  - r-mass=7.3_50=r351h96ca727_0
  - r-matrix=1.2_14=r351h96ca727_0
  - r-memoise=1.1.0=r351h6115d3f_0
  - r-mgcv=1.8_24=r351h96ca727_0
  - r-munsell=0.5.0=r351h6115d3f_0
  - r-nlme=3.1_137=r351ha65eedd_0
  - r-pillar=1.3.0=r351h6115d3f_0
  - r-pkgconfig=2.0.1=r351h6115d3f_0
  - r-plogr=0.2.0=r351h6115d3f_0
  - r-plyr=1.8.4=r351h29659fb_0
  - r-prettyunits=1.0.2=r351hf348343_0
  - r-purrr=0.2.5=r351h96ca727_0
  - r-r6=2.2.2=r351h6115d3f_0
  - r-rcolorbrewer=1.1_2=r351h6115d3f_0
  - r-rcpp=0.12.18=r351h29659fb_0
  - r-reshape2=1.4.3=r351h29659fb_0
  - r-rlang=0.2.1=r351h96ca727_0
  - r-rsqlite=2.1.1=r351h29659fb_0
  - r-scales=0.5.0=r351h29659fb_0
  - r-stringi=1.2.4=r351h29659fb_0
  - r-stringr=1.3.1=r351h6115d3f_0
  - r-tibble=1.4.2=r351h96ca727_0
  - r-tidyselect=0.2.4=r351h29659fb_0
  - r-utf8=1.1.4=r351h96ca727_0
  - r-viridislite=0.3.0=r351h6115d3f_0
  - r-withr=2.1.2=r351h6115d3f_0
  - readline=7.0=h7b6447c_5
  - retrying=1.3.3=py36_2
  - rpy2=2.9.1=py36r351h035aef0_0
  - samtools=1.9=h10a08f8_12
  - scikit-learn=0.20.3=py36hd81dba3_0
  - scipy=1.2.1=py36h7c811a0_0
  - seaborn=0.10.0=py_0
  - setuptools=41.0.1=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - sqlite=3.28.0=h7b6447c_0
  - statsmodels=0.9.0=py36h3010b51_1000
  - tensorboard=1.8.0=py36hf484d3e_0
  - tensorflow=1.8.0=h01c6a4e_0
  - tensorflow-base=1.8.0=py36hee38f2d_0
  - tensorflow-gpu=1.8.0=h7b35bdc_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=hbc83047_0
  - tktable=2.10=h14c3975_0
  - tornado=6.0.3=py36h7b6447c_3
  - tqdm=4.7.2=py36_0
  - werkzeug=0.15.2=py_0
  - wheel=0.33.4=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - deepsignal==0.1.5
    - joypy==0.2.2
    - nanocomp==1.10.1
    - ont-albacore==2.3.4
    - ont-fast5-api==3.0.0
    - progressbar33==2.4
    - psutil==5.6.7
prefix: /home/liuya/anaconda3/envs/nanoai

